import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.min.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ToastContainer
					autoClose={3000}
					bodyClassName={""}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					position="top-center"
					pauseOnHover
					theme="colored"
				/>

				<div className="min-h-screen px-5 sm:px-8 md:px-10 lg:px-24 flex flex-col items-center justify-center bg-slate-100 relative">
					<Navbar />
					<div className="container mx-auto pt-14 sm:pt-16 pt:h-20">{children}</div>
				</div>
			</body>
		</html>
	);
}
